version: '3'
services:
  dbmysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
        - ./db:/docker-entrypoint-initdb.d
    healthcheck:
        test: ["CMD", "mysqladmin","ping", "-h", "localhost", '-u', '-root', '-p$$MYSQL_ROOT_PASSWORD' ]
        timeout: 20s
        retries: 10
  web:
      build: .
      container_name: gin
      depends_on:
       dbmysql:
        condition: service_healthy
      ports:
      - "3000:3000"
